# Generated by Django 4.2.11 on 2024-07-26 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
