# Generated by Django 4.2.11 on 2024-07-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
