# Generated by Django 4.2.11 on 2024-07-30 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0007_question_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
