# Generated by Django 4.2.11 on 2024-07-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0009_question_time_limit_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
