# Generated by Django 4.2.11 on 2024-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0014_question_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default='option1', max_length=255),
        ),
    ]
