# Generated by Django 4.2.11 on 2024-07-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0015_remove_question_exam_question_correct_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
