# Generated by Django 4.2.14 on 2024-08-07 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0020_alter_question_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
