# Generated by Django 4.2.14 on 2024-08-09 11:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0021_alter_question_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_name',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Default question text'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='selected_option',
            field=models.CharField(default='option1', max_length=255),
        ),
        migrations.AlterField(
            model_name='proctoringsession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
        migrations.AlterField(
            model_name='proctoringsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
