# Generated by Django 4.2.14 on 2024-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0022_remove_question_question_name_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.DurationField(),
        ),
    ]
