# Generated by Django 4.2.14 on 2024-08-10 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0023_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
