# Generated by Django 4.2.14 on 2024-08-10 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0024_userresponse_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
