# Generated by Django 4.2.14 on 2024-08-12 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0025_alter_userresponse_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics','Mathematics')], default='Physics', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Mark for Review', 'Mark for Review'), ('Not Visited', 'Not Visited'), ('Not Answered', 'Not Answered')], default='Not Answered', max_length=50),
        ),
    ]
