# Generated by Django 4.2.15 on 2024-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0031_alter_proctoringsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringsession',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing', max_length=50),
        ),
    ]
