# Generated by Django 5.1.2 on 2024-11-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0033_exam_user_examparticipant_user_proctoringevent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
    ]
