# Generated by Django 5.1.4 on 2024-12-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0034_remove_exam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification3',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamParticipant',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Notification1',
        ),
        migrations.DeleteModel(
            name='Notification2',
        ),
        migrations.DeleteModel(
            name='Notification3',
        ),
        migrations.DeleteModel(
            name='ProctoringEvent',
        ),
        migrations.DeleteModel(
            name='ProctoringSession',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
