# Generated by Django 5.1.5 on 2025-02-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0037_proctoringsession_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
    ]
