# Generated by Django 5.1.5 on 2025-03-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0038_remove_examparticipant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='exam',
        ),
        migrations.DeleteModel(
            name='ExamParticipant',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ProctoringEvent',
        ),
        migrations.DeleteModel(
            name='ProctoringSession',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
