# Generated by Django 5.1.5 on 2025-03-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0040_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
