# Generated by Django 4.2.11 on 2024-07-24 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus_not_eligible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_eligible', 'Not Eligible')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStatus_not_selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_selected', 'Not Selected')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStatus_selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('selected', 'Selected')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('experience_yr', models.CharField(default='0-100', max_length=10)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'),
                                                ('contractual', 'Contarctual')], default='full_time', max_length=20)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('intermediate', 'Intermediate'), ('mid-senior', 'Mid-Senior'),
                                                ('BBA/BBM', 'BBA/BBM'), ('Associate', 'Associate'), ('no_experience','No-Experience'),
                                                ('internship', 'Internship'), ('expert', 'Expert')], default='fresher',max_length=20)),
                ('category', models.CharField(choices=[('Developer', 'Developer'), ('Coder', 'Coder'), ('Finance','Finance'),
                                                ('Accounting', 'Accounting'), ('Artist', 'Artist'), ('Marketing','Marketing'),
                                                ('UI/UX', 'UI/UX'), ('Engineer', 'Engineer'), ('Product', 'Product'),
                                                ('Content Writer', 'Content Writer')], default='Developer',max_length=50)),
                ('skills', models.CharField(max_length=1000)),
                ('workplaceTypes', models.CharField(choices=[('Hybrid', 'Hybrid'), ('On-site', 'On-site'),
                                                ('Remote', 'Remote')], default='On-site', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Unknown Candidate', max_length=255)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('phone_number', models.CharField(default='123-456-7890', max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(default='No cover letter provided')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('not_selected', 'Not Selected'), ('not_eligible', 'Not Eligible')], default='pending', max_length=20)),
                ('skills', models.CharField(max_length=1000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job')),
            ],
        ),
    ]
