# Generated by Django 4.2.11 on 2024-07-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_company_description_company_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='description', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(default='sector', max_length=100),
        ),
    ]
