# Generated by Django 4.2.11 on 2024-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='academic_projects',
            field=models.TextField(default='academic_projects'),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifiations',
            field=models.TextField(default='certifiations'),
        ),
    ]
