# Generated by Django 4.2.11 on 2024-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_resume_academic_projects_resume_certifiations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus_under_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('under_review', 'under_review')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
            ],
        ),
    ]
