# Generated by Django 4.2.11 on 2024-08-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0006_candidatestatus_under_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='certifiations',
            new_name='certifications',
        ),
    ]
