# Generated by Django 4.2.11 on 2024-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_rename_certifiations_resume_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.AddField(
            model_name='company',
            name='sector_type',
            field=models.CharField(choices=[('Basic metals', 'Basic metals'), ('Beverages and tobacco', 'Beverages and tobacco'),
                                             ('Broadcasting', 'Broadcasting'), ('Food & beverage services', 'Food & beverage services'),
                                             ('Services to buildings', 'Services to buildings'), ('Accommodation', 'Accommodation'),
                                            ('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Air transport', 'Air transport'),
                                            ('Architectural & related', 'Architectural & related'), ('Arts & Entertainment', 'Arts & Entertainment'),
                                            ('Auxiliary services', 'Auxiliary services'), ('Legal & accounting', 'Legal & accounting'),
                                            ('Office administration', 'Office administration'), ('Insurance & pensions', 'Insurance & pensions'),
                                            ('Repair & installation', 'Repair & installation'), ('Public service & defence', 'Public service & defence'),
                                            ('Film & music', 'Film & music'), ('Financial services', 'Financial services'), ('Food & beverage services', 'Food & beverage services'),
                                            ('Food products', 'Food products'), ('Furniture', 'Furniture'), ('Civil engineering', 'Civil engineering'),
                                            ('Coal, oil & gas; Mining & related', 'Coal, oil & gas; Mining & related'), ('Coke & refining (chemicals etc.)', 'Coke & refining (chemicals etc.)'),
                                            ('Computer programming', 'Computer programming'), ('Computers', 'Computers'), ('Construction', 'Construction'),
                                            ('Residential care', 'Residential care'), ('Specialised construction', 'Specialised construction'),
                                            ('Wearing apparel; Leather, etc', 'Wearing apparel; Leather, etc'), ('Coal, oil & gas; Mining & related', 'Coal, oil & gas; Mining & related'),
                                            ('Head offices', 'Head offices'), ('Membership organisations', 'Membership organisations'),
                                            ('Office administration', 'Office administration'), ('Other non-metallic', 'Other non-metallic'),
                                            ('Other personal service', 'Other personal service'), ('Other professional', 'Other professional'),
                                            ('Land transport', 'Land transport'), ('Legal & accounting', 'Legal & accounting'), ('Libraries', 'Libraries'),
                                            ('Rental & leasing', 'Rental & leasing'), ('Basic metals', 'Basic metals'), ('Other non-metallic', 'Other non-metallic'),
                                            ('Computer programming', 'Computer programming'), ('Coal, oil & gas; Mining & related', 'Coal, oil & gas; Mining & related'),
                                            ('Film & music', 'Film & music'), ('Machinery', 'Machinery'), ('Manufacturing', 'Manufacturing'),
                                            ('Membership organisations', 'Membership organisations'), ('Metal products', 'Metal products'),
                                            ('Motor vehicles', 'Motor vehicles'), ('Sale of motor vehicles', 'Sale of motor vehicles'),
                                            ('Insurance & pensions', 'Insurance & pensions'), ('Other personal service', 'Other personal service'),
                                            ('Other professional', 'Other professional'), ('Paper', 'Paper'), ('Pharmaceuticals', 'Pharmaceuticals'),
                                            ('Postal', 'Postal'), ('Printing & recording', 'Printing & recording'), ('Public service & defence', 'Public service & defence'),
                                            ('Publishing activities', 'Publishing activities'), ('Rubber & plastic', 'Rubber & plastic'),
                                            ('Sale of motor vehicles', 'Sale of motor vehicles'), ('Scientific research', 'Scientific research'),
                                            ('Security', 'Security'), ('Services to buildings', 'Services to buildings'), ('Sewerage', 'Sewerage'), ('Social work', 'Social work'),
                                            ('Specialised construction', 'Specialised construction'), ('Sport & recreation', 'Sport & recreation'),
                                            ('Air transport', 'Air transport'), ('Beverages and tobacco', 'Beverages and tobacco'),
                                            ('Land transport', 'Land transport'), ('Retail trade', 'Retail trade'), ('Telecommunications', 'Telecommunications'),
                                            ('Textiles', 'Textiles'), ('Transport equipment', 'Transport equipment'), ('Travel', 'Travel'),
                                            ('Water transport', 'Water transport'), ('Wholesale trade', 'Wholesale trade'), ('Coke & refining (chemicals etc.)', 'Coke & refining (chemicals etc.)'),
                                            ('Printing & recording', 'Printing & recording'), ('Real estate', 'Real estate'), ('Rental & leasing', 'Rental & leasing'),
                                            ('Repair & installation', 'Repair & installation'), ('Repair of goods', 'Repair of goods'), ('Residential care', 'Residential care'),
                                            ('Retail trade', 'Retail trade'), ('Rubber & plastic', 'Rubber & plastic'), ('Scientific research', 'Scientific research'),
                                            ('Sport & recreation', 'Sport & recreation'), ('Veterinary', 'Veterinary'), ('Warehousing', 'Warehousing'),
                                            ('Waste management', 'Waste management'), ('Water', 'Water'), ('Water transport', 'Water transport'),
                                            ('Wearing apparel; Leather, etc', 'Wearing apparel; Leather, etc'), ('Wholesale trade', 'Wholesale trade'),
                                            ('Wood', 'Wood'), ('Arts & Entertainment', 'Arts & Entertainment'), ('Civil engineering', 'Civil engineering'),
                                            ('Education', 'Education'), ('Electrical equipment', 'Electrical equipment'), ('Electricity, gas, etc', 'Electricity, gas, etc'),
                                            ('Employment activities', 'Employment activities'), ('Real estate', 'Real estate'), ('Transport equipment', 'Transport equipment'),
                                            ('Head offices', 'Head offices'), ('Health', 'Health'), ('Coal, oil & gas; Mining & related', 'Coal, oil & gas; Mining & related'),
                                            ('Electricity, gas, etc', 'Electricity, gas, etc'), ('Gambling', 'Gambling')], default='Basic metals', max_length=200),
        ),
    ]
