# Generated by Django 4.2.11 on 2024-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_remove_company_country_company_country_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Actor', 'Actor'), ('Administrative Assistant', 'Administrative Assistant'), ('Air Traffic Controller', 'Air Traffic Controller'), ('Animator', 'Animator'), ('Anthropologist', 'Anthropologist'), ('Archaeologist', 'Archaeologist'), ('Architect', 'Architect'), ('Artist', 'Artist'), ('Astronomer', 'Astronomer'), ('Athlete', 'Athlete'), ('Auditor', 'Auditor'), ('Baker', 'Baker'), ('Bartender', 'Bartender'), ('Biomedical Engineer', 'Biomedical Engineer'), ('Biologist', 'Biologist'), ('Bus Driver', 'Bus Driver'), ('Carpenter', 'Carpenter'), ('Cashier', 'Cashier'), ('Chef', 'Chef'), ('Chemical Engineer', 'Chemical Engineer'), ('Chiropractor', 'Chiropractor'), ('Civil Engineer', 'Civil Engineer'), ('Clinical Laboratory Technician', 'Clinical Laboratory Technician'), ('Coach', 'Coach'), ('Computer Programmer', 'Computer Programmer'), ('Construction Worker', 'Construction Worker'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Database Administrator', 'Database Administrator'), ('Dentist', 'Dentist'), ('Designer', 'Designer'), ('Dietitian', 'Dietitian'), ('Doctor', 'Doctor'), ('Editor', 'Editor'), ('Electrician', 'Electrician'), ('Engineer', 'Engineer'), ('Environmental Scientist', 'Environmental Scientist'), ('Event Planner', 'Event Planner'), ('Farmer', 'Farmer'), ('Fashion Designer', 'Fashion Designer'), ('Firefighter', 'Firefighter'), ('Flight Attendant', 'Flight Attendant'), ('Florist', 'Florist'), ('Geologist', 'Geologist'), ('Graphic Designer', 'Graphic Designer'), ('Hairdresser', 'Hairdresser'), ('Hotel Manager', 'Hotel Manager'), ('HR Manager', 'HR Manager'), ('Human Resources Specialist', 'Human Resources Specialist'), ('Insurance Agent', 'Insurance Agent'), ('Interpreter', 'Interpreter'), ('IT Manager', 'IT Manager'), ('Journalist', 'Journalist'), ('Judge', 'Judge'), ('Lawyer', 'Lawyer'), ('Librarian', 'Librarian'), ('Machinist', 'Machinist'), ('Marine Biologist', 'Marine Biologist'), ('Marketing Manager', 'Marketing Manager'), ('Mathematician', 'Mathematician'), ('Mechanic', 'Mechanic'), ('Medical Assistant', 'Medical Assistant'), ('Musician', 'Musician'), ('Network Administrator', 'Network Administrator'), ('Nutritionist', 'Nutritionist'), ('Occupational Therapist', 'Occupational Therapist'), ('Optician', 'Optician'), ('Painter', 'Painter'), ('Paramedic', 'Paramedic'), ('Pharmacist', 'Pharmacist'), ('Photographer', 'Photographer'), ('Physical Therapist', 'Physical Therapist'), ('Physicist', 'Physicist'), ('Podiatrist', 'Podiatrist'), ('Pilot', 'Pilot'), ('Plumber', 'Plumber'), ('Police Officer', 'Police Officer'), ('Postman', 'Postman'), ('Professor', 'Professor'), ('Project Manager', 'Project Manager'), ('Psychologist', 'Psychologist'), ('Real Estate Agent', 'Real Estate Agent'), ('Receptionist', 'Receptionist'), ('Reporter', 'Reporter'), ('Research Scientist', 'Research Scientist'), ('Sales Manager', 'Sales Manager'), ('Sales Representative', 'Sales Representative'), ('Secretary', 'Secretary'), ('Security Guard', 'Security Guard'), ('Social Worker', 'Social Worker'), ('Software Developer', 'Software Developer'), ('Software Engineer', 'Software Engineer'), ('Surgeon', 'Surgeon'), ('Taxi Driver', 'Taxi Driver'), ('Teacher', 'Teacher'), ('Technician', 'Technician'), ('Translator', 'Translator'), ('Travel Agent', 'Travel Agent'), ('Truck Driver', 'Truck Driver'), ('Veterinarian', 'Veterinarian'), ('Videographer', 'Videographer'), ('Waiter', 'Waiter'), ('Web Developer', 'Web Developer'), ('Writer', 'Writer'), ('Zoologist', 'Zoologist')], default='Employee',max_length=200),
        ),
    ]
