# Generated by Django 4.2.14 on 2024-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0012_alter_candidatestatus_not_eligible_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Coder', 'Coder'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Artist', 'Artist'), ('Marketing', 'Marketing'), ('UI/UX', 'UI/UX'), ('Engineer', 'Engineer'), ('Product', 'Product'), ('Content Writer', 'Content Writer')], default='Accounting', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Intermediate', 'Intermediate'), ('Mid-Senior', 'Mid-Senior'), ('Associate', 'Associate'), ('Internship', 'Internship'), ('Expert', 'Expert')], default='Fresher', max_length=50),
        ),
    ]
