# Generated by Django 4.2.14 on 2024-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_alter_job_category_alter_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('On-site', 'On-site'), ('Remote', 'Remote')], default='Pune', max_length=20),
        ),
    ]
