# Generated by Django 4.2.14 on 2024-08-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0014_job_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='locations',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], default='Pune', max_length=20),
        ),
    ]
