# Generated by Django 4.2.14 on 2024-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0017_alter_job_category_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='locations',
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
