# Generated by Django 4.2.14 on 2024-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0018_remove_job_locations_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workplaceTypes',
            field=models.CharField(max_length=50),
        ),
    ]
