# Generated by Django 4.2.14 on 2024-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0020_alter_job_category_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector_type',
            field=models.CharField(max_length=100),
        ),
    ]
