# Generated by Django 4.2.14 on 2024-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0021_alter_company_country_type_alter_company_sector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
