# Generated by Django 4.2.14 on 2024-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0022_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatus_not_eligible',
            name='status',
            field=models.CharField(default='not_eligible', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatestatus_not_selected',
            name='status',
            field=models.CharField(default='not_selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatestatus_selected',
            name='status',
            field=models.CharField(default='selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatestatus_under_review',
            name='status',
            field=models.CharField(default='under_review', max_length=20),
        ),
    ]
