# Generated by Django 4.2.14 on 2024-08-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0023_alter_candidatestatus_not_eligible_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='country_type',
            new_name='country_name',
        ),
    ]
