# Generated by Django 4.2.15 on 2024-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0024_rename_country_type_company_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
