# Generated by Django 4.2.15 on 2024-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0025_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus_rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='rejected', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CandidateStatus_not_selected',
        ),
    ]
