# Generated by Django 4.2.15 on 2024-09-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0026_candidatestatus_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='academic_projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='achievements_and_awards',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='resume',
            name='activities',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interests',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='resume',
            name='website_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='Not specified'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('contact_info', models.CharField(default='Not provided', max_length=100)),
                ('relationship', models.CharField(default='N/A', max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='job_portal.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Project', max_length=100)),
                ('description', models.TextField(default='No description')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='job_portal.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Not specified')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objective', to='job_portal.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Unknown', max_length=100)),
                ('company_name', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='No description')),
                ('resume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='job_portal.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_or_degree', models.CharField(default='Unknown', max_length=100)),
                ('school_or_university', models.CharField(default='Unknown', max_length=100)),
                ('grade_or_cgpa', models.CharField(default='N/A', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='job_portal.resume')),
            ],
        ),
    ]
