# Generated by Django 4.2.15 on 2024-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0028_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('publisher', models.CharField(default='Unknown', max_length=100)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('publisher', models.CharField(default='Unknown', max_length=100)),
                ('date_of_year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='achievements_and_awards',
        ),
    ]
