# Generated by Django 4.2.15 on 2024-09-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0029_achievements_publications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='date_of_year',
            new_name='date_of_publications',
        ),
    ]
