# Generated by Django 4.2.15 on 2024-09-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0030_rename_date_of_year_publications_date_of_publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
