# Generated by Django 4.2.15 on 2024-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0033_user_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='Attachment',
            field=models.FileField(default='Unknown', upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='bio',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='zipcode',
            field=models.CharField(default='522426', max_length=6),
        ),
    ]
