# Generated by Django 4.2.15 on 2024-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0034_remove_resume_name_resume_attachment_resume_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('contact_no', models.CharField(default='000-000-0000', max_length=20)),
                ('qualification', models.TextField(default='N/A')),
                ('skills', models.TextField(default='Not specified')),
            ],
        ),
    ]
