# Generated by Django 4.2.15 on 2024-09-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0036_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
    ]
