# Generated by Django 4.2.15 on 2024-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0037_remove_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.AddField(
            model_name='company',
            name='about_company',
            field=models.TextField(default='about_company', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='website_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(default='522426', max_length=6),
        ),
    ]
