# Generated by Django 4.2.15 on 2024-09-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0038_remove_company_description_company_about_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country_name',
        ),
    ]
