# Generated by Django 4.2.15 on 2024-09-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0041_alter_company_about_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='delete',
            new_name='is_deleted',
        ),
    ]
