# Generated by Django 4.2.15 on 2024-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0044_remove_message_recipient_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
