# Generated by Django 4.2.15 on 2024-09-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0045_company_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_status',
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
