# Generated by Django 4.2.15 on 2024-09-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0048_remove_application_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningquestion',
            name='job',
        ),
        migrations.DeleteModel(
            name='ScreeningAnswer',
        ),
        migrations.DeleteModel(
            name='ScreeningQuestion',
        ),
    ]
