# Generated by Django 4.2.15 on 2024-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0050_screeningquestion_screeninganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='with_promoting_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='without_promoting_job',
            field=models.BooleanField(default=False),
        ),
    ]
