# Generated by Django 4.2.15 on 2024-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0054_remove_usersubscription_current_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
