# Generated by Django 4.2.15 on 2024-09-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0056_remove_candidatestatus_not_eligible_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_primary',
        ),
    ]
