# Generated by Django 4.2.15 on 2024-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0058_membershipplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(default='Standard', max_length=10),
        ),
    ]
