# Generated by Django 4.2.15 on 2024-09-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0059_usersubscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
    ]
