# Generated by Django 4.2.15 on 2024-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0062_membershipplan_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('website', models.URLField()),
                ('phone', models.CharField(default='000-000-0000', max_length=20)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('university_type', models.CharField(default='Unknown', max_length=100)),
                ('about_college', models.CharField(default='about_college', max_length=255)),
                ('website_urls', models.CharField(default='Unknown', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zipcode', models.CharField(default='522426', max_length=6)),
                ('Attachment', models.FileField(default='Unknown', upload_to='attachments/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
