# Generated by Django 4.2.15 on 2024-09-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0064_studentenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnquiry',
        ),
    ]
