# Generated by Django 4.2.15 on 2024-09-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0065_delete_studentenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='job_portal.college')),
            ],
        ),
    ]
