# Generated by Django 4.2.15 on 2024-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0066_studentenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
