# Generated by Django 4.2.15 on 2024-09-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0067_studentenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_portal.college'),
        ),
    ]
