# Generated by Django 4.2.15 on 2024-09-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0068_job_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='college',
        ),
        migrations.CreateModel(
            name='Job1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('experience_yr', models.CharField(default='0-100', max_length=10)),
                ('job_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=1000)),
                ('workplaceTypes', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('questions', models.TextField(blank=True, null=True)),
                ('job_status', models.CharField(default='active', max_length=50)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('must_have_qualification', models.BooleanField(default=False)),
                ('filter', models.BooleanField(default=False)),
                ('source', models.CharField(default='LinkedIn', max_length=50)),
                ('card_number', models.CharField(blank=True, default='Not Provided', max_length=20, null=True)),
                ('expiration_code', models.CharField(blank=True, default='MM/YY', max_length=5, null=True)),
                ('security_code', models.CharField(blank=True, default='000', max_length=4, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='000000', max_length=10, null=True)),
                ('gst', models.CharField(blank=True, default='Not Provided', max_length=15, null=True)),
                ('promoting_job', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.college')),
            ],
        ),
    ]
