# Generated by Django 4.2.15 on 2024-09-30 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0069_remove_job_college_job1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('phone_number', models.CharField(default='123-456-7890', max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(default='No cover letter provided')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('skills', models.CharField(max_length=1000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job1')),
            ],
        ),
    ]
