# Generated by Django 4.2.15 on 2024-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0070_application1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('mobile_number', models.CharField(default='123-456-7890', max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
