# Generated by Django 4.2.15 on 2024-10-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0071_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
