# Generated by Django 4.2.15 on 2024-10-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0072_delete_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('mobile_number', models.CharField(default='123-456-7890', max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='job_portal.college')),
            ],
        ),
    ]
