# Generated by Django 4.2.15 on 2024-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0073_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='course',
            field=models.CharField(default='N/A', max_length=128),
        ),
    ]
