# Generated by Django 4.2.15 on 2024-10-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0074_studentenquiry_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='password',
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.college'),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='status',
            field=models.CharField(choices=[('replied', 'Replied'), ('not-replied', 'Not-Replied')], default='not-replied', max_length=20),
        ),
        migrations.CreateModel(
            name='CollegeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('course', models.CharField(default='N/A', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.college')),
            ],
        ),
    ]
