# Generated by Django 4.2.15 on 2024-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0077_jobrole_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
