# Generated by Django 4.2.15 on 2024-10-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0078_application_bio_application_education_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
