# Generated by Django 4.2.15 on 2024-10-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0080_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='role',
        ),
    ]
