# Generated by Django 4.2.15 on 2024-10-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0081_remove_interview_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
