# Generated by Django 4.2.15 on 2024-10-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0084_application_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='job',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='student',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='application',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='ScreeningAnswer',
        ),
    ]
