# Generated by Django 4.2.15 on 2024-10-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0086_application_screeninganswer_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRole',
        ),
    ]
