# Generated by Django 5.1.2 on 2024-10-23 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0088_alter_application_student'),
        ('login', '0014_remove_new_user_education_new_user_educations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expiration_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='promoting_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='expiration_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='promoting_job',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='achievements',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='application1',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='candidatestatus_not_eligible',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='candidatestatus_not_eligible',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='candidatestatus_rejected',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='candidatestatus_rejected',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='candidatestatus_selected',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='candidatestatus_selected',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='candidatestatus_under_review',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='candidatestatus_under_review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='certification',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='college',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='collegeenquiry',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='job1',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='message',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='message',
            name='company_recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='job_portal.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='objective',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='project',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='publications',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='publications',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='reference',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='screeninganswer',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='screeninganswer',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='screeninganswer',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='screeninganswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='screeningquestion',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AddField(
            model_name='screeningquestion',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='student',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.CreateModel(
            name='College_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('college_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clg_recipient', to='job_portal.college')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
                ('university_in_charge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='College_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('university_in_charge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='job_portal.college_message')),
            ],
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
