# Generated by Django 5.1.2 on 2024-10-23 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0089_remove_usersubscription_current_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('job_postings', models.PositiveIntegerField(default=0)),
                ('featured_jobs', models.PositiveIntegerField(default=0)),
                ('job_duration_days', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='college_recipient',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='application1',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_not_eligible',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_not_eligible',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_rejected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_rejected',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_selected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_selected',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_under_review',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_under_review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='collegeenquiry',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='education',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='screeninganswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='screeningquestion',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='screeningquestion',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='student',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='university_in_charge',
        ),
        migrations.AddField(
            model_name='job',
            name='card_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expiration_code',
            field=models.CharField(blank=True, default='MM/YY', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='gst',
            field=models.CharField(blank=True, default='Not Provided', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, default='000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='promoting_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='security_code',
            field=models.CharField(blank=True, default='000', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='card_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='expiration_code',
            field=models.CharField(blank=True, default='MM/YY', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='job1',
            name='gst',
            field=models.CharField(blank=True, default='Not Provided', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='job1',
            name='postal_code',
            field=models.CharField(blank=True, default='000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job1',
            name='promoting_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job1',
            name='security_code',
            field=models.CharField(blank=True, default='000', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.CharField(default='Standard', max_length=15)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_portal.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='College_Attachment',
        ),
        migrations.DeleteModel(
            name='College_Message',
        ),
    ]
