# Generated by Django 5.1.2 on 2024-10-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0090_membershipplan_and_more'),
        ('login', '0015_remove_new_user_educations_new_user_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
            preserve_default=False,
        ),
    ]
