# Generated by Django 5.1.2 on 2024-10-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0095_candidate1status_not_eligible_and_more'),
        ('login', '0018_new_user_is_deleted_alter_consultant_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_message',
            old_name='sender_jobseeker',
            new_name='receiptent_job_seeker',
        ),
        migrations.RenameField(
            model_name='college_message',
            old_name='sender_newuser',
            new_name='receiptent_new_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_job_seeker',
            new_name='receiptent_job_seeker',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_new_user',
            new_name='receiptent_new_user',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='college_recipient',
        ),
        migrations.RemoveField(
            model_name='collegeenquiry',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_recipient',
        ),
        migrations.AddField(
            model_name='college_message',
            name='university_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='collegeenquiry',
            name='new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AddField(
            model_name='message',
            name='company_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='collegeenquiry',
            name='status',
            field=models.CharField(choices=[('replied', 'Replied'), ('not-replied', 'Not-Replied')], default='not-replied', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('advertisement_placement', models.CharField(max_length=100)),
                ('time_duration', models.CharField(max_length=50)),
                ('investment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_audience', models.CharField(max_length=100)),
                ('company_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('advertisement_placement', models.CharField(max_length=100)),
                ('time_duration', models.CharField(max_length=50)),
                ('investment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_audience', models.CharField(max_length=100)),
                ('university_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('course_to_purchase', models.CharField(max_length=100)),
                ('quantity_of_leads', models.IntegerField()),
                ('location_for_leads', models.CharField(max_length=100)),
                ('intake_year', models.IntegerField()),
                ('university_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('course_to_purchase', models.CharField(max_length=100)),
                ('quantity_of_leads', models.IntegerField()),
                ('location_for_leads', models.CharField(max_length=100)),
                ('intake_year', models.IntegerField()),
                ('company_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge')),
            ],
        ),
    ]
