# Generated by Django 5.1.2 on 2024-10-28 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0096_rename_sender_jobseeker_college_message_receiptent_job_seeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unique_job_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='unique_job_id_as_int',
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
    ]
