# Generated by Django 5.1.2 on 2024-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0097_job_unique_job_id_job_unique_job_id_as_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterModelTable(
            name='job1',
            table='job1',
        ),
    ]
