# Generated by Django 5.1.2 on 2024-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0098_alter_application_resume_alter_job1_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_urls',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
