# Generated by Django 5.1.2 on 2024-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0099_alter_company_website_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
