# Generated by Django 5.1.2 on 2024-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0103_messages_alter_attachment_message_messages1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment1',
            name='message',
        ),
        migrations.RemoveField(
            model_name='college_attachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='receiptent_job_seeker',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='receiptent_new_user',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiptent_job_seeker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiptent_new_user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='company',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_candidate',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_company',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_student',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='student',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='college',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_candidate',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_college',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_student',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Attachment1',
        ),
        migrations.DeleteModel(
            name='College_Attachment',
        ),
        migrations.DeleteModel(
            name='College_Message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Messages1',
        ),
    ]
