# Generated by Django 5.1.2 on 2024-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0104_remove_attachment1_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=models.CharField(default='about_company', max_length=2000),
        ),
    ]
