# Generated by Django 5.1.2 on 2024-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0106_alter_company_about_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=models.CharField(default='about_company', max_length=2000),
        ),
    ]
