# Generated by Django 5.1.3 on 2024-12-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0109_bookmark'),
        ('login', '0019_remove_companyincharge_user_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.job')),
                ('job1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.job1')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
            options={
                'unique_together': {('jobseeker', 'job', 'job1')},
            },
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
