# Generated by Django 5.1.3 on 2024-12-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0110_savedjob_delete_bookmark'),
        ('login', '0019_remove_companyincharge_user_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='jobseeker',
            new_name='JobSeeker',
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('JobSeeker', 'job', 'job1')},
        ),
    ]
