# Generated by Django 5.1.3 on 2024-12-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0111_rename_jobseeker_savedjob_jobseeker_and_more'),
        ('login', '0019_remove_companyincharge_user_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='JobSeeker',
            new_name='jobseeker',
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('jobseeker', 'job', 'job1')},
        ),
    ]
