# Generated by Django 5.1.3 on 2024-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0112_rename_jobseeker_savedjob_jobseeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='original_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
