# Generated by Django 5.1.3 on 2024-12-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0113_savedjob_original_job_id'),
        ('login', '0019_remove_companyincharge_user_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobForNewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('original_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.job')),
                ('job1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.job1')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user')),
            ],
            options={
                'unique_together': {('new_user', 'job', 'job1')},
            },
        ),
    ]
