# Generated by Django 5.1.4 on 2025-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0116_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
