# Generated by Django 5.1.4 on 2025-01-02 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0117_alter_resume_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
