# Generated by Django 5.1.4 on 2025-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0119_alter_publications_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
