# Generated by Django 5.1.4 on 2025-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0121_alter_achievements_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
