# Generated by Django 5.1.4 on 2025-01-02 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0123_alter_certification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_achievements',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_achievements',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_certification',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobseeker_education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobseeker_experience',
            name='company_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_experience',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_experience',
            name='job_title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_objective',
            name='text',
            field=models.TextField(blank=True, default='Not specified', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_project',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_project',
            name='project_link',
            field=models.TextField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_project',
            name='title',
            field=models.CharField(blank=True, default='Untitled Project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_publications',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_publications',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_reference',
            name='contact_info',
            field=models.CharField(blank=True, default='Not provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_reference',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_reference',
            name='relationship',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='Attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='activities',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='bio',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='interests',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='languages',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
