# Generated by Django 5.1.4 on 2025-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0124_alter_jobseeker_achievements_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
