# Generated by Django 5.1.4 on 2025-01-03 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0125_alter_company_employee_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_urls',
            field=models.JSONField(default=list),
        ),
    ]
