# Generated by Django 5.1.4 on 2025-01-03 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0126_alter_company_established_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='founded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
