# Generated by Django 5.1.4 on 2025-01-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0128_college_profile_picture_company_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker_resume',
            name='Attachment',
        ),
    ]
