# Generated by Django 5.1.4 on 2025-01-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0130_jobseeker_resume_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='jobseeker_resume',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profile_picture',
        ),
    ]
