# Generated by Django 5.1.4 on 2025-01-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0134_remove_jobseeker_resume_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker_resume',
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='jobseeker_resume',
            name='delete',
        ),
    ]
