# Generated by Django 5.1.4 on 2025-01-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0135_remove_jobseeker_resume_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='college',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='delete',
        ),
    ]
