# Generated by Django 5.1.4 on 2025-01-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0136_remove_college_attachment_remove_college_is_deleted_and_more'),
        ('login', '0026_remove_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeenquiry',
            name='university_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
    ]
