# Generated by Django 5.1.4 on 2025-01-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0137_collegeenquiry_university_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeenquiry',
            name='college',
        ),
    ]
