# Generated by Django 5.1.4 on 2025-01-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0140_alter_collegeenquiry_new_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='college',
        ),
    ]
