# Generated by Django 5.1.5 on 2025-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0142_new_user_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_enquiry',
            name='country_code',
            field=models.CharField(default='+91', max_length=3),
        ),
    ]
