# Generated by Django 5.1.5 on 2025-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0143_new_user_enquiry_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_enquiry',
            name='clg_id',
            field=models.IntegerField(default=0),
        ),
    ]
