# Generated by Django 5.1.5 on 2025-02-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0144_new_user_enquiry_clg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user_enquiry',
            name='college',
        ),
        migrations.RemoveField(
            model_name='new_user_enquiry',
            name='university_in_charge',
        ),
    ]
