# Generated by Django 5.1.5 on 2025-02-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0145_remove_new_user_enquiry_college_and_more'),
        ('login', '0028_new_user_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_enquiry',
            name='university_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
    ]
