# Generated by Django 5.1.5 on 2025-02-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0148_colleges_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user_enquiry',
            name='collegeName',
        ),
    ]
