# Generated by Django 5.1.5 on 2025-02-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0149_remove_new_user_enquiry_collegename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colleges_Location',
        ),
    ]
