# Generated by Django 5.1.5 on 2025-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0150_delete_colleges_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user_enquiry',
            name='clg_id',
            field=models.CharField(blank=True, default='Null', max_length=400, null=True),
        ),
    ]
