from django.urls import path # type: ignore
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register',views.Register.as_view(),name='register'),
    path('next',views.Next.as_view(),name="next"),
    path('login',views.Login.as_view(),name="login"),
    path('forgot',views.Forgot_view.as_view(),name="forgot"),
    path('forgot2',views.Forgot2_view.as_view(),name="forgot2"),
    path('get-csrf-token/', views.get_csrf_token, name='get_csrf_token'),
    path('register/company/', views.RegisterCompanyInChargeView.as_view(), name='register_company_incharge_api'),
    path('register/university/', views.RegisterUniversityInChargeView.as_view(), name='register_university_incharge_api'),
    path('register/consultant/', views.RegisterConsultantView.as_view(), name='register_consultant_incharge_api'),
    path('job_portal', views.Subscriber_view.as_view(), name='job_portal'),
    path('subscriber', views.Subscriber_view1.as_view(), name='subscriber'),
    path('verify_otp1',views.Verify_view.as_view(),name="verify_otp1"),
    path('resend-otp/', views.ResendOtpView.as_view(), name='resend_otp'),
    path('login/company/', views.LoginCompanyInChargeView.as_view(), name='login_company'),
    path('login/university/', views.LoginUniversityInChargeView.as_view(), name='login_university'),
    path('login/consultant/', views.LoginConsultantView.as_view(), name='login_consultant'),
    path('logout/student/', views.StudentLogoutView.as_view(), name='student-logout'),
    path('logout/company/', views.LogoutCompanyInChargeView.as_view(), name='company-logout'),
    path('logout/university/', views.LogoutUniversityView.as_view(), name='university-logout'),
    path('logout/consultant/', views.LogoutConsultantView.as_view(), name='consultant-logout'),
    path('register/job-seeker/', views.RegisterJobSeekerView.as_view(), name='register-job-seeker'),
    path('login/job_seeker/', views.LoginJobSeekerView.as_view(), name='login_job_seeker'),
    path('logout/job-seeker/', views.JobSeekerLogoutView.as_view(), name='job-seeker-logout'),
    path('change-password-company/', views.ChangePasswordCompanyInChargeView.as_view(), name='change_password_company_in_charge'),
    path('change-password-university/', views.ChangePasswordUniversityInChargeView.as_view(), name='change_password_university'),
    path('consultant/change-password/', views.ChangePasswordConsultantView.as_view(), name='change_password_consultant'),
    path('job-seeker/change-password/', views.ChangePasswordJobSeekerView.as_view(), name='change_password_job_seeker'),
    path('company/delete-account/', views.DeleteCompanyInChargeAccountView.as_view(), name='delete_company_account'),
    path('job-seeker/delete-account/', views.DeleteJobSeekerAccountView.as_view(), name='delete_job_seeker_account'),
    path('university/delete-account/', views.DeleteUniversityAccountView.as_view(), name='delete_university_account'),
    path('user/delete-account/', views.DeleteUserAccountView.as_view(), name='delete_user_account'),
    path('consultant/delete-account/', views.DeleteConsultantAccountView.as_view(), name='consultant-delete-account'),
    path('student-reset-password/', views.ResetPasswordNewUserView.as_view(), name='reset_student_password'),
    path('company-forgot',views.Company_Forgot_view.as_view(),name="forgot"),
    path('company-verify_otp',views.Company_Verify_view.as_view(),name="verify_otp1"),
    path('company-resend-otp', views.CompanyResendOtpView.as_view(), name='resend_otp'),
    path('company-forgot2',views.CompanyForgot2_view.as_view(),name="forgot2"),
    path('college-forgot/', views.ForgotUniversityInChargeView.as_view(), name='forgot_university_in_charge'),
    path('college-verify-otp/', views.VerifyUniversityInChargeOTPView.as_view(), name='verify_university_in_charge_otp'),
    path('college-resend-otp/', views.ResendUniversityInChargeOtpView.as_view(), name='resend_university_in_charge_otp'),
    path('college-reset-password/', views.ResetPasswordUniversityInChargeView.as_view(), name='reset_university_in_charge_password'),
    path('jobseeker-forgot/', views.ForgotJobseekerView.as_view(), name='forgot_jobseeker'),
    path('jobseeker-verify-otp/', views.VerifyJobseekerOTPView.as_view(), name='verify_jobseeker_otp'),
    path('jobseeker-resend-otp/', views.ResendJobseekerOtpView.as_view(), name='resend_otp'),
    path('jobseeker-reset-password/', views.ResetPasswordJobseekerView.as_view(), name='forgot_jobseeker_password'),
    path('consultant-forgot/', views.ForgotConsultantView.as_view(), name='forgot_consultant'),
    path('consultant-verify-otp/', views.VerifyConsultantOTPView.as_view(), name='verify_consultant_otp'),
    path('consultant-resend-otp/', views.ResendConsultantOtpView.as_view(), name='resend-consultant-otp'),
    path('consultant-reset-password/', views.ResetPasswordConsultantView.as_view(), name='reset-consultant-password'),
    path('submit-contact/', views.submit_contact_form, name='submit-contact'),
    path('submit-question/', views.submit_question, name='submit-question'),
    path('submit-answer/<int:question_id>/', views.submit_answer, name='submit-answer'),
    path("submit-review/", views.submit_admission_review, name="submit-review"),


    #path('verify-token/', views.verify_token, name='verify_token'),
    #path('verify-linkedin/', views.verify_linkedin_token, name='verify_linkedin'),
    #path('search/', views.search, name='search'),

]
