# Generated by Django 4.2.15 on 2024-10-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='desired_job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new_user',
            name='job_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new_user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('job_seeker', 'Job Seeker')], default='student', max_length=20),
        ),
    ]
