# Generated by Django 4.2.15 on 2024-10-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyincharge',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='consultant',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='new_user',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='universityincharge',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
