# Generated by Django 4.2.15 on 2024-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_jobseeker_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
