# Generated by Django 5.1.2 on 2024-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_new_user_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='education',
        ),
        migrations.AddField(
            model_name='new_user',
            name='educations',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyincharge',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityincharge',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
