# Generated by Django 5.1.2 on 2024-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_new_user_education_new_user_educations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='educations',
        ),
        migrations.AddField(
            model_name='new_user',
            name='education',
            field=models.CharField(default='Not specifie1d', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyincharge',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='universityincharge',
            name='token',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
