# Generated by Django 5.1.2 on 2024-10-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_companyincharge_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user',
            old_name='education',
            new_name='educations',
        ),
    ]
