# Generated by Django 5.1.2 on 2024-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_education_new_user_educations'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='educations',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityincharge',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
