# Generated by Django 5.1.2 on 2024-10-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_new_user_is_deleted_alter_consultant_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyincharge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='universityincharge',
            name='user',
        ),
    ]
