# Generated by Django 5.1.4 on 2024-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_companyincharge_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
