# Generated by Django 5.1.4 on 2024-12-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_jobseeker_otp_code_jobseeker_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityincharge',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='universityincharge',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
