# Generated by Django 5.1.4 on 2025-01-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_universityincharge_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyincharge',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='companyincharge',
            name='otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='universityincharge',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='universityincharge',
            name='otp_generated_at',
        ),
    ]
