# Generated by Django 5.1.4 on 2025-01-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_remove_companyincharge_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
