# Generated by Django 5.1.4 on 2025-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_jobseeker_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(default='Unknown', upload_to='profile_pics/'),
        ),
    ]
