# Generated by Django 5.1.5 on 2025-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityincharge',
            name='agreed_to_terms',
            field=models.BooleanField(default=True),
        ),
    ]
