# Generated by Django 5.1.5 on 2025-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_new_user_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityincharge',
            name='trimmed_university_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
