# Generated by Django 5.1.5 on 2025-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionReview1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('other_college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(max_length=255)),
                ('other_course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='IN', max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('course_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('apply', models.CharField(default='applied', max_length=20)),
                ('anvil_reservation_benefits', models.BooleanField()),
                ('benefit', models.CharField(default='Benefits', max_length=20)),
                ('gd_pi_admission', models.BooleanField()),
                ('class_size', models.IntegerField()),
                ('opted_hostel', models.BooleanField()),
                ('college_provides_placements', models.BooleanField()),
                ('hostel_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admission_process', models.TextField()),
                ('course_curriculum_faculty', models.TextField()),
                ('fees_structure_scholarship', models.TextField()),
                ('liked_things', models.TextField()),
                ('disliked_things', models.TextField()),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='uploads/profile_photos/')),
                ('campus_photos', models.FileField(blank=True, null=True, upload_to='uploads/campus_photos/')),
                ('certificate_id_card', models.FileField(blank=True, null=True, upload_to='uploads/certificates/')),
                ('graduation_certificate', models.FileField(blank=True, null=True, upload_to='uploads/graduation_certificates/')),
                ('agree_terms', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
