# Generated by Django 5.1.5 on 2025-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_admissionreview1_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredColleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(default='Null', max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=3)),
                ('mobile_number', models.CharField(default='Null', max_length=15)),
                ('password', models.CharField(default='null', max_length=128)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('college_person_name', models.CharField(default='Null', max_length=255)),
                ('agreed_to_terms', models.BooleanField(default=True)),
            ],
        ),
    ]
