# Generated by Django 5.1.5 on 2025-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_unregisteredcolleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityincharge',
            name='clg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unregisteredcolleges',
            name='clg_id',
            field=models.IntegerField(default=0),
        ),
    ]
