# Generated by Django 5.1.5 on 2025-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_universityincharge_clg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unregisteredcolleges',
            name='clg_id',
        ),
    ]
