# Generated by Django 5.1.5 on 2025-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_remove_universityincharge_trimmed_university_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityincharge',
            name='clg_id',
            field=models.CharField(blank=True, default='Null', max_length=400, null=True),
        ),
    ]
