# Generated by Django 5.1.2 on 2024-11-20 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('university', 'University'), ('company', 'Company'), ('jobseeker', 'JobSeeker'), ('new_user', 'NewUser')], max_length=20)),
                ('sender_id', models.IntegerField()),
                ('receiver_type', models.CharField(choices=[('university', 'University'), ('company', 'Company'), ('jobseeker', 'JobSeeker'), ('new_user', 'NewUser')], max_length=20)),
                ('receiver_id', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
