# Generated by Django 5.1.2 on 2024-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_object_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_object_id',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
