# Generated by Django 5.1.5 on 2025-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_url',
            field=models.URLField(default='https://res.cloudinary.com/your-cloud-name/image/upload/vdefault/default_file_placeholder.png', max_length=500),
        ),
    ]
