from django.contrib import admin # type: ignore
from .models import  Achievements, Advertisement, Application, CollegeAdvertisement, CollegeMembership, CollegeScreeningAnswer, CollegeScreeningQuestion, CompanyScreeningAnswer, CompanyScreeningQuestion,  Education,  Certification, College, CollegeEnquiry, Job, Company,JobSeeker_Achievements, JobSeeker_Certification, JobSeeker_Education, JobSeeker_Experience, JobSeeker_Objective, JobSeeker_Project, JobSeeker_Publications, JobSeeker_Reference, JobSeeker_Resume, Membership, Publications, Resume, Project, Objective, Experience, Reference, Application1, Job1, StudentEnquiry, Visitor

admin.site.register(Job)
admin.site.register(Application)
admin.site.register(Company)
admin.site.register(Project)
admin.site.register(Reference)
admin.site.register(Publications)
admin.site.register(Resume)
admin.site.register(Experience)
admin.site.register(Education)
admin.site.register(Achievements)
admin.site.register(Certification)
admin.site.register(Objective)
admin.site.register(College)
admin.site.register(CollegeEnquiry)
admin.site.register(Application1)
admin.site.register(Visitor)
admin.site.register(Job1)
admin.site.register(CompanyScreeningQuestion)
admin.site.register(CompanyScreeningAnswer)
admin.site.register(CollegeScreeningQuestion)
admin.site.register(CollegeScreeningAnswer)
admin.site.register(StudentEnquiry)
admin.site.register(JobSeeker_Resume)
admin.site.register(JobSeeker_Objective)
admin.site.register(JobSeeker_Education)
admin.site.register(JobSeeker_Experience)
admin.site.register(JobSeeker_Project)
admin.site.register(JobSeeker_Reference)
admin.site.register(JobSeeker_Certification)
admin.site.register(JobSeeker_Achievements)
admin.site.register(JobSeeker_Publications)
admin.site.register(Membership)
admin.site.register(CollegeMembership)
admin.site.register(Advertisement)
admin.site.register(CollegeAdvertisement)